### ISSUE TITLE
[ERROR]: Could not pass event ChunkLoadEvent to Bookshelf v3.0.6.3

### ISSUE THREAD

**Issue by joex92** [LOOHP/Bookshelf#7]
I'm getting this error often, idk what it is...
```yaml
[03:27:32 ERROR]: Could not pass event ChunkLoadEvent to Bookshelf v3.0.6.3
java.util.concurrent.RejectedExecutionException: Task com.loohp.bookshelf.BookshelfManager$$Lambda$10870/0x00000008032e0000@6122a284 rejected from java.util.concurrent.ThreadPoolExecutor@64d5be8f[Terminated, pool size = 0, active threads = 0, queued tasks = 0, completed tasks = 6]
        at java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(ThreadPoolExecutor.java:2057) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor.reject(ThreadPoolExecutor.java:827) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor.execute(ThreadPoolExecutor.java:1357) ~[?:?]
        at com.loohp.bookshelf.BookshelfManager.executeAsyncTask(BookshelfManager.java:218) ~[Bookshelf-3.0.6.3.jar:?]
        at com.loohp.bookshelf.BookshelfManager.onChunkLoad(BookshelfManager.java:244) ~[Bookshelf-3.0.6.3.jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor1476.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.17.1.jar:git-Purpur-1385]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.17.1.jar:git-Purpur-1385]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.17.1.jar:git-Purpur-1385]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:624) ~[patched_1.17.1.jar:git-Purpur-1385]
        at net.minecraft.world.level.chunk.Chunk.loadCallback(Chunk.java:971) ~[patched_1.17.1.jar:git-Purpur-1385]
        at net.minecraft.server.level.PlayerChunk.lambda$updateFutures$22(PlayerChunk.java:873) ~[patched_1.17.1.jar:git-Purpur-1385]
        at net.minecraft.server.level.PlayerChunkMap$CallbackExecutor.run(PlayerChunkMap.java:182) ~[patched_1.17.1.jar:git-Purpur-1385]
        at net.minecraft.server.level.PlayerChunk.a(PlayerChunk.java:883) ~[patched_1.17.1.jar:git-Purpur-1385]
        at net.minecraft.server.level.ChunkMapDistance.a(ChunkMapDistance.java:215) ~[patched_1.17.1.jar:git-Purpur-1385]
        at net.minecraft.server.level.ChunkProviderServer.tickDistanceManager(ChunkProviderServer.java:846) ~[patched_1.17.1.jar:git-Purpur-1385]
        at net.minecraft.server.level.ChunkMapDistance.addPriorityTicket(ChunkMapDistance.java:418) ~[patched_1.17.1.jar:git-Purpur-1385]
        at net.minecraft.server.level.ChunkMapDistance.markUrgent(ChunkMapDistance.java:345) ~[patched_1.17.1.jar:git-Purpur-1385]
        at net.minecraft.server.level.ChunkProviderServer.getChunkFutureMainThread(ChunkProviderServer.java:763) ~[patched_1.17.1.jar:git-Purpur-1385]
        at net.minecraft.server.level.ChunkProviderServer.getChunkAt(ChunkProviderServer.java:667) ~[patched_1.17.1.jar:git-Purpur-1385]
        at net.minecraft.world.level.World.getChunkAt(World.java:677) ~[patched_1.17.1.jar:git-Purpur-1385]
        at net.minecraft.world.level.World.getType(World.java:1016) ~[patched_1.17.1.jar:git-Purpur-1385]
        at org.bukkit.craftbukkit.v1_17_R1.block.CraftBlock.getNMS(CraftBlock.java:74) ~[patched_1.17.1.jar:git-Purpur-1385]
        at org.bukkit.craftbukkit.v1_17_R1.block.CraftBlock.isLiquid(CraftBlock.java:622) ~[patched_1.17.1.jar:git-Purpur-1385]
        at org.shimado.classes.NaturalSpawning.spawnRating(NaturalSpawning.java:40) ~[Relics.jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor310.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.17.1.jar:git-Purpur-1385]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.17.1.jar:git-Purpur-1385]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.17.1.jar:git-Purpur-1385]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:624) ~[patched_1.17.1.jar:git-Purpur-1385]
        at org.bukkit.craftbukkit.v1_17_R1.event.CraftEventFactory.callCreatureSpawnEvent(CraftEventFactory.java:737) ~[patched_1.17.1.jar:git-Purpur-1385]
        at org.bukkit.craftbukkit.v1_17_R1.event.CraftEventFactory.doEntityAddEventCalling(CraftEventFactory.java:642) ~[patched_1.17.1.jar:git-Purpur-1385]
        at net.minecraft.server.level.WorldServer.addEntity0(WorldServer.java:1477) ~[patched_1.17.1.jar:git-Purpur-1385]
        at net.minecraft.server.level.WorldServer.addEntity(WorldServer.java:1389) ~[patched_1.17.1.jar:git-Purpur-1385]
        at org.bukkit.craftbukkit.v1_17_R1.CraftWorld.addEntityToWorld(CraftWorld.java:972) ~[patched_1.17.1.jar:git-Purpur-1385]
        at org.bukkit.craftbukkit.v1_17_R1.CraftRegionAccessor.addEntity(CraftRegionAccessor.java:503) ~[patched_1.17.1.jar:git-Purpur-1385]
        at org.bukkit.craftbukkit.v1_17_R1.CraftRegionAccessor.spawn(CraftRegionAccessor.java:479) ~[patched_1.17.1.jar:git-Purpur-1385]
        at org.bukkit.craftbukkit.v1_17_R1.CraftRegionAccessor.spawn(CraftRegionAccessor.java:473) ~[patched_1.17.1.jar:git-Purpur-1385]
        at org.bukkit.craftbukkit.v1_17_R1.CraftRegionAccessor.spawn(CraftRegionAccessor.java:459) ~[patched_1.17.1.jar:git-Purpur-1385]
        at org.bukkit.craftbukkit.v1_17_R1.CraftRegionAccessor.spawnEntity(CraftRegionAccessor.java:367) ~[patched_1.17.1.jar:git-Purpur-1385]
        at me.xxastaspastaxx.dimensions.addons.base.DimensionsBaseAddon.onPortalTick(DimensionsBaseAddon.java:589) ~[?:?]
        at me.xxastaspastaxx.dimensions.completeportal.CompletePortal$1.run(CompletePortal.java:283) ~[Dimensions.jar:?]
        at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[patched_1.17.1.jar:git-Purpur-1385]
        at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483) ~[patched_1.17.1.jar:git-Purpur-1385]
        at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1574) ~[patched_1.17.1.jar:git-Purpur-1385]
        at net.minecraft.server.dedicated.DedicatedServer.b(DedicatedServer.java:493) ~[patched_1.17.1.jar:git-Purpur-1385]
        at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1490) ~[patched_1.17.1.jar:git-Purpur-1385]
        at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1283) ~[patched_1.17.1.jar:git-Purpur-1385]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:321) ~[patched_1.17.1.jar:git-Purpur-1385]
        at java.lang.Thread.run(Thread.java:831) [?:?]
[03:27:32 ERROR]: Could not pass event ChunkUnloadEvent to Bookshelf v3.0.6.3
java.util.concurrent.RejectedExecutionException: Task com.loohp.bookshelf.BookshelfManager$$Lambda$11042/0x00000008032e0228@338b8fa1 rejected from java.util.concurrent.ThreadPoolExecutor@64d5be8f[Terminated, pool size = 0, active threads = 0, queued tasks = 0, completed tasks = 6]
        at java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(ThreadPoolExecutor.java:2057) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor.reject(ThreadPoolExecutor.java:827) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor.execute(ThreadPoolExecutor.java:1357) ~[?:?]
        at com.loohp.bookshelf.BookshelfManager.executeAsyncTask(BookshelfManager.java:218) ~[Bookshelf-3.0.6.3.jar:?]
        at com.loohp.bookshelf.BookshelfManager.onChunkUnload(BookshelfManager.java:254) ~[Bookshelf-3.0.6.3.jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor1475.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.17.1.jar:git-Purpur-1385]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.17.1.jar:git-Purpur-1385]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.17.1.jar:git-Purpur-1385]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:624) ~[patched_1.17.1.jar:git-Purpur-1385]
        at net.minecraft.world.level.chunk.Chunk.unloadCallback(Chunk.java:1003) ~[patched_1.17.1.jar:git-Purpur-1385]
        at net.minecraft.server.level.PlayerChunk.lambda$updateFutures$10(PlayerChunk.java:677) ~[patched_1.17.1.jar:git-Purpur-1385]
        at net.minecraft.server.level.PlayerChunkMap$CallbackExecutor.run(PlayerChunkMap.java:182) ~[patched_1.17.1.jar:git-Purpur-1385]
        at net.minecraft.server.level.PlayerChunk.a(PlayerChunk.java:687) ~[patched_1.17.1.jar:git-Purpur-1385]
        at net.minecraft.server.level.ChunkMapDistance.a(ChunkMapDistance.java:215) ~[patched_1.17.1.jar:git-Purpur-1385]
        at net.minecraft.server.level.ChunkProviderServer.tickDistanceManager(ChunkProviderServer.java:846) ~[patched_1.17.1.jar:git-Purpur-1385]
        at net.minecraft.server.level.ChunkProviderServer.tick(ChunkProviderServer.java:929) ~[patched_1.17.1.jar:git-Purpur-1385]
        at net.minecraft.server.level.WorldServer.doTick(WorldServer.java:756) ~[patched_1.17.1.jar:git-Purpur-1385]
        at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1635) ~[patched_1.17.1.jar:git-Purpur-1385]
        at net.minecraft.server.dedicated.DedicatedServer.b(DedicatedServer.java:493) ~[patched_1.17.1.jar:git-Purpur-1385]
        at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1490) ~[patched_1.17.1.jar:git-Purpur-1385]
        at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1283) ~[patched_1.17.1.jar:git-Purpur-1385]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:321) ~[patched_1.17.1.jar:git-Purpur-1385]
        at java.lang.Thread.run(Thread.java:831) [?:?]
```
this is the plugins list:
```yaml
Plugins (112): 
3DItems (1.6.0)
AdvancedArmorStands (1.17.3.0)
AdvancedRegionMarket (3.3.5)
ajStartCommands (2.0.3)
AlwaysVoidTP (1.2.0)
AnnouncerPlus (1.2.5)
ArmorSetEffects (2.2.4)
AutoPickup (1.3.4-SNAPSHOT)
BetterConcrete (1.7.0)
BetterGiants (2.7)
BetterNav (1.0.7)
BKCommonLib (1.17.1-v3)
BloodNight (0.10.7)
Bookshelf (3.0.6.3)
Carz (7.2)
ChestSort (11.5.1)
Citizens (2.0.28-SNAPSHOT (build 2359))
ClientDetector (2.1.2)
CMILib (1.0.3.9)
Coins (1.10.8)
CoreProtect (20.1)
CustomCrafting (1.7.1.3)
CustomTime (2.1.1)
DailyRewards (1.1.0)
DamageIndicator (1.2.12)
DangerousCaves (2.2.14-SNAPSHOT)
DeadSouls (1.6)
Dimensions (2.0.1)
DiscordSRV (1.24.0)
DiscordSRV-Staff-Chat (1.4.0)
DoorsReloaded (1.1.2)
EasyUnsafeEnchants (1.2)
EconomyShopGUI (3.8.0)
Elevator (3.11.4)
EnchantGui (3.5.1)
Enchantssquared (1.6)
Essentials (2.19.0)
EssentialsGeoIP (2.19.0)
EssentialsSpawn (2.19.0)
Evolutions (1.1.8)
ExtraContexts (2.0-SNAPSHOT)
ExtractableEnchantments (8.4)
FastAsyncWorldEdit (1.17-167;df8b280)
Geyser-Spigot (1.4.3-SNAPSHOT)
GriefPrevention (16.17.1-2b69191)
GSit ([6.0.2.1])
HeadDB (2.4.3)
HealthBar (1.6.3)
HolographicDisplays (2.4.9)
IdleBot (1.2.1)
Images (2.2.3)
InfiniteVouchers (2.2.1)
InteractionVisualizer (1.16.3.12)
Jobs (5.0.0.8)
LevelledMobs (3.1.7 b508)
LuckPerms (5.3.55)
Maintenance (3.0.7)
Maplands (1.1)
mcMMO (2.1.201-SNAPSHOT)
MineChess (1.12.1)
MobsToEggs (1.5.5_5)
MoreArmour (2.0.6)
MoreMobHeads (1.15_1.0.21)
MoreOres (1.12.1)
Multiverse-CommandDestination (1.2.2)
Multiverse-Core (4.3.1-SNAPSHOT-b860)
Multiverse-Inventories (4.2.2-SNAPSHOT-bUNKNOWN)
Multiverse-NetherPortals (4.2.2-SNAPSHOT-b804)
Multiverse-Portals (4.2.2-SNAPSHOT-b850)
MusicBox (2.0.5)
MyCommand (5.7.1)
NexEngine (2.0.7.4)
NoteBlockAPI (2.0-SNAPSHOT)
Oh_the_dungeons_youll_go (15.4)
Pl3xMap (1.0.0-BETA-162)
PlaceholderAPI (2.10.10)
PlasmoVoice (1.0.6)
PlugMan (2.2.5)
PortalGun (2.2.2)
ProtocolLib (4.7.0)
RealLogin (24-8-2021 Build 1)
Relics (2.2)
Scoreboard (3.4.4)
Shopkeepers (2.13.3)
ShulkerPacks (1.5.16)
SignBoard (1.6.10)
SkinsRestorer (14.1.4)
SmoothTimber (1.17.8)
SpigotDash (0.3.9 BETA)
StayPut (1.2.1)
StreamingDrops (7.2)
TabTPS (1.3.10)
Tamablefoxes (2.1.5-SNAPSHOT)
Terra (5.4.1-BETA+efd1665c)
TerraformGenerator (4.6.4)
Tweakin (3.2.1)
Vault (1.7.3-b131)
ViaBackwards (4.0.2-SNAPSHOT)
ViaVersion (4.0.2-SNAPSHOT)
voicechat (1.17.1-1.1.2)
VoidGen (2.0)
Wardrobe (1.4.2)
Waterex (1.1.2)
WebPlugin (1.4R)
WebStats (1.4.1)
Wild (2.29-7da6164)
WolfyUtilities (1.7.3.0)
WorldBorder (2.1.4)
WorldEditSelectionVisualizer (2.1.0)
WorldGuard (7.0.5+3827266)
WowSuchCleaner (1.9.2)
ZombieApocalypse (1.4.2)
```

**Comment by LOOHP** [comment]
Can you try version 3.6.0.4 ?

**Comment by joex92** [comment]
well, this happened months ago, but now it's working... thanks
